import { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import StatusBadge from '../components/employee/StatusBadge';
import { approvePurchaseRequest, getManagerInbox, rejectPurchaseRequest, returnPurchaseRequest } from '../services/purchaseRequestService';
import { formatCurrency, formatDate, getPageContent } from '../utils/employeeHelpers';
import { getApiErrorMessage } from '../utils/apiErrors';

const STATUS_FILTERS = ['APPROVED', 'CLOSED', 'PENDING', 'REJECTED'];

export default function DepartmentRequests() {
  const navigate = useNavigate(); const location = useLocation(); const [requests, setRequests] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(null); const [remarks, setRemarks] = useState({}); const [error, setError] = useState(''); const [statuses, setStatuses] = useState([]); const urgentOnly = Boolean(location.state?.urgentOnly);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setRequests(getPageContent(await getManagerInbox({ page: 0, size: 50 }))); } catch (err) { setError(getApiErrorMessage(err, 'Unable to load team requests.')); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const filteredRequests = useMemo(() => requests.filter((request) => (statuses.length === 0 || statuses.includes(request.status)) && (!urgentOnly || request.priority === 'URGENT')), [requests, statuses, urgentOnly]);
  const toggleStatus = (status) => setStatuses((current) => current.includes(status) ? current.filter((item) => item !== status) : [...current, status]);
  const action = async (request, type) => { const note = (remarks[request.id] || '').trim(); if ((type === 'reject' || type === 'return') && !note) { setError('Remarks are required when rejecting or returning a request.'); return; } setBusy(request.id); setError(''); try { if (type === 'approve') await approvePurchaseRequest(request.id, note); else if (type === 'reject') await rejectPurchaseRequest(request.id, note); else await returnPurchaseRequest(request.id, note); await load(); } catch (err) { setError(getApiErrorMessage(err, 'Unable to update the request.')); } finally { setBusy(null); } };
  return <div className="container-fluid mt-4"><div className="mb-4"><h2>Team Requests</h2><p className="text-muted mb-0">Review and action purchase requests assigned to you.</p></div>{error && <div className="alert alert-danger">{error}</div>}<div className="d-flex flex-wrap align-items-center gap-3 mb-3">{STATUS_FILTERS.map((status) => <label className="form-check form-check-inline mb-0" key={status}><input className="form-check-input" type="checkbox" checked={statuses.includes(status)} onChange={() => toggleStatus(status)} /><span className="form-check-label">{status.charAt(0) + status.slice(1).toLowerCase()}</span></label>)}{urgentOnly && <button type="button" className="btn btn-sm btn-outline-warning" onClick={() => navigate('/dashboard/team-requests', { replace: true })}><i className="bi bi-exclamation-triangle me-1" />Urgent only ×</button>}</div><div className="card shadow-sm"><div className="table-responsive">{loading ? <div className="text-center py-5"><div className="spinner-border text-primary" /></div> : filteredRequests.length === 0 ? <div className="text-center text-muted py-5">No requests match the selected filters.</div> : <table className="table table-hover align-middle mb-0"><thead className="table-light"><tr><th>Request</th><th>Employee</th><th>Title</th><th>Amount</th><th>Date</th><th>Status</th><th>Remarks</th><th>Actions</th></tr></thead><tbody>{filteredRequests.map((request) => { const pending = request.status === 'PENDING'; return <tr key={request.id}><td><code>{request.requestNumber}</code></td><td>{request.requesterName || '—'}</td><td>{request.title || '—'}</td><td>{formatCurrency(request.totalAmount)}</td><td>{formatDate(request.createdAt)}</td><td><StatusBadge status={request.status} /></td><td>{pending ? <input className="form-control form-control-sm" value={remarks[request.id] || ''} onChange={(event) => setRemarks((current) => ({ ...current, [request.id]: event.target.value }))} placeholder="Remarks" /> : request.managerRemarks || '—'}</td><td><div className="d-flex gap-1 flex-wrap"><button className="btn btn-sm btn-outline-primary" onClick={() => navigate(`/manager/requests/${request.id}`)}>View</button>{pending && <><button className="btn btn-sm btn-success" disabled={busy === request.id} onClick={() => action(request, 'approve')}>Approve</button><button className="btn btn-sm btn-danger" disabled={busy === request.id} onClick={() => action(request, 'reject')}>Reject</button><button className="btn btn-sm btn-warning" disabled={busy === request.id} onClick={() => action(request, 'return')}>Return</button></>}</div></td></tr>; })}</tbody></table>}</div></div></div>;
}
