import { useCallback, useEffect, useState } from 'react';
import { getFinanceInvoices } from '../../services/financeService';
import { formatCurrency, formatDate, getPageContent, getPageMeta } from '../../utils/employeeHelpers';
import { getApiErrorMessage } from '../../utils/apiErrors';

const FinanceInvoicesPage = () => {
  const [invoices, setInvoices] = useState([]); const [page, setPage] = useState(0);
  const [meta, setMeta] = useState({ number: 0, totalPages: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await getFinanceInvoices({ page }); const data = response?.data ?? response; setInvoices(getPageContent(data)); setMeta(getPageMeta(data)); } catch (err) { setError(getApiErrorMessage(err, 'Unable to load invoices.')); } finally { setLoading(false); } }, [page]);
  useEffect(() => { load(); }, [load]);
  return <><div className="dashboard-page-header"><h1>Invoices</h1><p className="text-muted mb-0">Invoices and their real payment status.</p></div>{error && <div className="alert alert-danger">{error}</div>}{loading ? <div className="text-center py-5"><div className="spinner-border text-primary" /></div> : invoices.length === 0 ? <div className="employee-table-card text-center py-5 text-muted">No invoices available.</div> : <div className="employee-table-card table-responsive"><table className="table employee-table align-middle mb-0"><thead><tr><th>Invoice</th><th>PO</th><th>Request</th><th>Vendor</th><th>Invoice Date</th><th>Due Date</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id}><td className="fw-semibold">{invoice.invoiceNumber}</td><td>{invoice.purchaseOrderNumber || '—'}</td><td>{invoice.purchaseRequestNumber || '—'}</td><td>{invoice.vendorName || '—'}</td><td>{formatDate(invoice.invoiceDate)}</td><td>{formatDate(invoice.dueDate)}</td><td>{formatCurrency(invoice.totalAmount)}</td><td>{formatCurrency(invoice.paidAmount)}</td><td>{formatCurrency(invoice.balanceAmount)}</td><td><span className={`badge text-bg-${invoice.status === 'PAID' ? 'success' : invoice.status === 'CANCELLED' ? 'secondary' : 'warning'}`}>{invoice.status?.replaceAll('_', ' ')}</span></td></tr>)}</tbody></table></div>}{meta.totalPages > 1 && <div className="d-flex justify-content-center gap-2 mt-3"><button className="btn btn-sm btn-outline-secondary" disabled={meta.number === 0} onClick={() => setPage((current) => current - 1)}>Previous</button><span className="align-self-center small text-muted">Page {meta.number + 1} of {meta.totalPages}</span><button className="btn btn-sm btn-outline-secondary" disabled={meta.number >= meta.totalPages - 1} onClick={() => setPage((current) => current + 1)}>Next</button></div>}</>;
};
export default FinanceInvoicesPage;
